"""VBScript output for GLF."""

from .flatten import STOP, Emission
from .hwmap import HardwareMap
from .values import GRID_MS

HEADER = "' GENERATED BY PSC (scripts/psc) - DO NOT EDIT.\n' Sources: {sources}\n' Rebuild: npm run psc-compile\n"


def light_string(name: str, e: Emission) -> str:
    if e.out is STOP:
        return f"{name}|100|stop"
    brightness = int(round(e.out.brightness))
    text = f"{name}|100|000000" if brightness <= 0 else f"{name}|{brightness}|{e.out.color}"
    if e.fade > 0:
        text += f"|{e.fade}"
    return text


def seconds(ms: int) -> str:
    return f"{ms / 1000:.2f}"


def emit_show(name: str, length: int, emissions: dict[str, list[Emission]], order: list[str]) -> str:
    by_time: dict[int, list[str]] = {}
    for light in order:
        for e in emissions.get(light, []):
            by_time.setdefault(e.t, []).append(light_string(light, e))
    # GLF stops a non-looping show as soon as its last step runs, ignoring that
    # step's duration. An empty final step makes the show last its full length.
    # It goes 10ms early when there is room, so loop periods stay exact.
    last = max(by_time, default=0)
    end_marker = length - GRID_MS if length - GRID_MS > last else length
    by_time[end_marker] = []
    times = sorted(by_time)
    lines = [f'    With CreateGlfShow("{name}")']
    for i, t in enumerate(times):
        end = times[i + 1] if i + 1 < len(times) else max(length, t + GRID_MS)
        lines.append(f"        With .AddStep(Null, Null, {seconds(end - t)})  ' t={seconds(t)}s")
        entries = by_time[t]
        if not entries:
            lines.append("            ' end of show")
            lines.append("        End With")
            continue
        if len(entries) <= 3:
            lines.append("            .Lights = Array(" + ", ".join(f'"{s}"' for s in entries) + ")")
        else:
            lines.append("            .Lights = Array( _")
            for j, s in enumerate(entries):
                tail = ", _" if j < len(entries) - 1 else ")"
                lines.append(f'                "{s}"{tail}')
        lines.append("        End With")
    lines.append("    End With")
    return "\n".join(lines)


def emit_file(shows: list[str], hw: HardwareMap, sources: str) -> str:
    bulbs = [l for l in (hw.light(n) for n in hw.order) if l.proxy]
    out = [HEADER.format(sources=sources)]
    out.append("' Backglass proxy lights: Array(light name, B2S/DOF id, on-threshold 0-254).")
    out.append("' Read by PscBackglassMirror in psc_backglass_mirror.vbs.")
    out.append("Function PscBackglassBulbs()")
    if bulbs:
        rows = [f'Array("{b.name}", {b.b2s_id}, {b.threshold})' for b in bulbs]
        out.append("    PscBackglassBulbs = Array( _")
        for j, row in enumerate(rows):
            out.append(f"        {row}{', _' if j < len(rows) - 1 else ')'}")
    else:
        out.append("    PscBackglassBulbs = Array()")
    out.append("End Function")
    out.append("")
    out.append("Sub CreatePscShows()")
    out.extend(shows)
    out.append("End Sub")
    return "\n".join(out) + "\n"
