'*******************************************
'  PSC backglass mirror
'*******************************************
' Backglass bulbs are driven through hidden proxy lights (bg_*) in the
' glf_lights collection. GLF treats them like any other light, so groups,
' show priorities, and cleanup when a show stops all work for them.
'
' Every frame this copies each proxy's on/off state to its B2S bulb via DOF,
' sending a command only when the state changes. The bulb list comes from
' PscBackglassBulbs(), generated by PSC into src/game/shows/psc_shows.vbs.
' Bulbs are on/off only: "on" means the proxy's brightest color channel is
' above the bulb's threshold (0-254, default 0).

Dim psc_bg_bulbs : psc_bg_bulbs = Empty
Dim psc_bg_state : Set psc_bg_state = CreateObject("Scripting.Dictionary")

Sub PscBackglassMirror()
    If IsEmpty(psc_bg_bulbs) Then psc_bg_bulbs = PscBackglassBulbs()
    Dim bulb, name, isOn
    For Each bulb In psc_bg_bulbs
        name = bulb(0)
        If glf_lightNames.Exists(name) Then
            isOn = (PscMaxChannel(glf_lightNames(name).Color) > bulb(2))
            If Not psc_bg_state.Exists(name) Then psc_bg_state.Add name, Not isOn
            If psc_bg_state(name) <> isOn Then
                psc_bg_state(name) = isOn
                If isOn Then
                    DOF bulb(1), 1
                Else
                    DOF bulb(1), 0
                End If
            End If
        End If
    Next
End Sub

Function PscMaxChannel(color)
    Dim c : c = CLng(color)
    Dim m : m = c And 255
    If ((c \ 256) And 255) > m Then m = (c \ 256) And 255
    If ((c \ 65536) And 255) > m Then m = (c \ 65536) And 255
    PscMaxChannel = m
End Function
